version: '3.8'
services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase_data:/pb_data
    environment:
      POCKETBASE_ADMIN_EMAIL: admin@chitra.local
      POCKETBASE_ADMIN_PASSWORD: admin123456
